# Generated by Django 2.2 on 2019-04-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('room_number', models.IntegerField()),
                ('no_bed', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='hotel',
            name='meals',
            field=models.ManyToManyField(blank=True, related_name='hotel', to='hotel.Meal'),
        ),
    ]
