# Generated by Django 2.2 on 2019-04-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20190427_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='hotel', to='hotel.Room'),
        ),
    ]
