# Generated by Django 2.2 on 2019-04-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotel_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='hot', to='hotel.Room'),
        ),
    ]
