# Generated by Django 2.2 on 2019-04-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20190427_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='hotel.Room'),
        ),
    ]
