# Generated by Django 2.2 on 2019-04-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_auto_20190427_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='book',
            field=models.BooleanField(default=False),
        ),
    ]
