# Generated by Django 2.2 on 2019-04-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_hotel_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='book',
        ),
        migrations.AddField(
            model_name='room',
            name='book',
            field=models.BooleanField(default=False),
        ),
    ]
