# Generated by Django 2.2 on 2019-04-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_auto_20190427_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='rating',
            field=models.CharField(choices=[('Master', 'Master'), ('Executive Suite', 'Executive Suite')], default='Master', max_length=100),
        ),
    ]
