# Generated by Django 2.2 on 2019-04-27 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0010_auto_20190427_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='rating',
            field=models.CharField(choices=[('Honey moon suites', 'Honey moon suites'), ('Master', 'Master'), ('Executive Suite', 'Executive Suite'), ('Superior Rooms', 'Superior Rooms'), ('Ambassadorial Rooms', 'Ambassadorial Rooms'), ('Standard Rooms', 'Standard Rooms')], default='Master', max_length=100),
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_created=True)),
                ('end_date', models.DateField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
